#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

curl -Lo manifest-tool "https://github.com/estesp/manifest-tool/releases/download/v1.0.2/manifest-tool-linux-amd64"
chmod +x manifest-tool

./manifest-tool push from-spec multi-arch-manifest-latest.yaml
./manifest-tool push from-spec multi-arch-manifest-minimal.yaml
