image: realsimonmicro/py-kms-multiarch:minimal
manifests:
  - image: realsimonmicro/py-kms-multiarch:minimal-amd64
    platform:
      architecture: amd64
      os: linux
  - image: realsimonmicro/py-kms-multiarch:minimal-arm32v7
    platform:
      architecture: arm
      os: linux
      variant: v7
  - image: realsimonmicro/py-kms-multiarch:minimal-arm64v8
    platform:
      architecture: arm64
      os: linux
      variant: v8
