name: Build next-tags

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  bake-next:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/docker-py3-kms/Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: ghcr.io/py-kms-organization/py-kms:python3-next
          build-args: |
            BUILD_COMMIT=${{ github.sha }}
            BUILD_BRANCH=${{ github.ref_name }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/docker-py3-kms-minimal/Dockerfile
          platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: ghcr.io/py-kms-organization/py-kms:latest-next,ghcr.io/py-kms-organization/py-kms:minimal-next
          build-args: |
            BUILD_COMMIT=${{ github.sha }}
            BUILD_BRANCH=${{ github.ref_name }}
